export const userActionTypes = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",

  EMAIL_SIGNUP_START: "EMAIL_SIGNUP_START",
  EMAIL_SIGNUP_SUCCESS: "EMAIL_SIGNUP_SUCCESS",
  EMAIL_SIGNUP_FAILURE: "EMAIL_SIGNUP_FAILURE",

  CHECK_USER_SESSION: "CHECK_USER_SESSION",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  GOOGLE_SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
  GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
  EMAIL_SIGNIN_SUCCESS: "EMAIL_SIGNIN_SUCCESS",
  EMAIL_SIGNIN_FAILURE: "EMAIL_SIGNIN_FAILURE",
};
